backport stable-16.0.x:
  - head-branch: ['^weblate']

backport stable-15.10.x:
  - head-branch: ['^weblate']

backport stable-15.5.x:
  - head-branch: ['^weblate']

backport stable-14.10.x:
  - head-branch: ['^weblate']